# Limine v8.7.0 configuration syntax. Kernel requests protocol base revision 3.
timeout: 3
interface_branding: UTAMO OS

/UTAMO OS
    protocol: limine
    path: boot():/boot/utamo-kernel.elf
    module_path: boot():/boot/initramfs.cpio
    module_cmdline: utamo-initramfs
    resolution: 1024x768x32
    kaslr: no
    paging_mode: 4level
